[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-google-contacts-server"
version = "0.1.0"
description = "MCP server for Google Contacts integration"
readme = "README.md"
authors = [
    {name = "Rayan Zaki", email = "rayan.hassici@ensia.edu.dz"}
]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp",
    "google-api-python-client",
    "google-auth",
    "google-auth-oauthlib",
]

[project.urls]
"Homepage" = "https://github.com/rayanzaki/mcp-google-contacts-server"
"Bug Tracker" = "https://github.com/rayanzaki/mcp-google-contacts-server/issues"

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["config", "formatters", "google_contacts_service", "main", "tools"]

[project.scripts]
mcp-google-contacts = "main:main"
